### ISSUE TITLE
create function to traverse months/years

### ISSUE THREAD

**Issue by sep160112138** [cse110-fa22-group32/cse110-fa22-group32#40]
create function that will add event listener to traversal buttons

for now assume that each calendar will only have a month/day object if an event/task exists

**Comment by sep160112138** [comment]
Need to have an implementation of displaying months on calendar

**Comment by ghost** [comment]
If you mean displaying events of a month on calendar, then that can be achieved by calling the method Show(year, month) under class Calendar.
